﻿CREATE DATABASE QL_DTDD1
GO
USE QL_DTDD1
GO

CREATE TABLE LOAI
(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)

CREATE TABLE SANPHAM
(
	MASP INT IDENTITY(1,1) PRIMARY KEY,
	TENSP NVARCHAR(30),
	DUONGDAN VARCHAR(20),
	GIA MONEY,
	MOTA NVARCHAR(50),
	MALOAI INT,
	CONSTRAINT FK_SANPHAM_LOAI FOREIGN KEY (MALOAI) REFERENCES LOAI (MALOAI)
)

CREATE TABLE KHACHHANG
(
	MAKH INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(30),
	DIENTHOAI VARCHAR(15),
	GIOITINH NVARCHAR(3),
	SOTHICH NVARCHAR(50),
	EMAIL VARCHAR(50),
	MATKHAU VARCHAR(50)
)

CREATE TABLE GIOHANG
(
	MAGH INT IDENTITY(1,1) PRIMARY KEY,
	MAKH INT,
	MASP INT,
	SOLUONG INT,
	NGAY DATE,
	CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY (MAGH) REFERENCES KHACHHANG (MAKH),
	CONSTRAINT FK_GIOHANG_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
)

-- BẢNG LOAI
INSERT INTO LOAI VALUES ('Nokia')
INSERT INTO LOAI VALUES ('SamSung')
INSERT INTO LOAI VALUES ('Motorola')
INSERT INTO LOAI VALUES ('LG')
INSERT INTO LOAI VALUES ('Oppo')
INSERT INTO LOAI VALUES ('Iphone')
INSERT INTO LOAI VALUES ('Bphone')
INSERT INTO LOAI VALUES ('Xiaomi')
INSERT INTO LOAI VALUES ('Vivo')
INSERT INTO LOAI VALUES ('Realme')

-- BẢNG SANPHAM
INSERT INTO SANPHAM 
VALUES ('N701', 'N07.jpg', 2000000, N'Nâng cấp BN', 1)
INSERT INTO SANPHAM 
VALUES ('72', 'N72.jpg', 2100000, N'Nâng cấp BN, 2 màu Đen, Xám', 1)
INSERT INTO SANPHAM 
VALUES ('N6030', 'N6030.jpg', 3000000, N'Nâng cấp BN, Gấp', 1)
INSERT INTO SANPHAM 
VALUES ('N6200', 'N6200.jpg', 3200000, N'Nâng cấp BN, màu Đen, Xám, Đỏ, Bạc', 1)
INSERT INTO SANPHAM 
VALUES ('GalaxyA6', 'GalaxyA6.jpg', 5200000, N'Nâng cấp BN, màu Đen, Xám, Đỏ, Bạc', 2)
INSERT INTO SANPHAM 
VALUES ('GalaxyA9', 'GalaxyA9.jpg', 5500000, N'Nâng cấp BN, màu Đen, Xám, Đỏ, Bạc', 2)
INSERT INTO SANPHAM 
VALUES ('GalaxyJ5', 'GalaxyJ5.jpg', 6000000, N'Nâng cấp BN, màu Đen, Xám, Đỏ, Bạc', 2)
INSERT INTO SANPHAM 
VALUES ('MotoE5', 'MotoE5.jpg', 2300000, N'Unlimited Extra', 3)
INSERT INTO SANPHAM 
VALUES ('Iphone12', 'Iphone12.jpg', 9800000, N'128GB', 6)
INSERT INTO SANPHAM 
VALUES ('Iphone12Pro', 'Iphone12Pro.jpg', 11300000, N'256GB', 6)
INSERT INTO SANPHAM 
VALUES ('Nokia8.3', 'Nokia83.jpg', 8500000, N'5G, Camera 64MP', 1)
INSERT INTO SANPHAM 
VALUES ('GalaxyS21', 'GalaxyS21.jpg', 18000000, N'5G, 128GB, Camera 64MP', 2)
INSERT INTO SANPHAM 
VALUES ('Galaxy Z Fold3', 'Zfold3.jpg', 40000000, N'Màn hình gập, 5G', 2)
INSERT INTO SANPHAM 
VALUES ('MotoG100', 'MotoG100.jpg', 12000000, N'Flagship, Snapdragon 870', 3)
INSERT INTO SANPHAM 
VALUES ('LGWing', 'LGWing.jpg', 15000000, N'Màn hình xoay độc đáo', 4)
INSERT INTO SANPHAM 
VALUES ('OppoReno6', 'Reno6.jpg', 9500000, N'Camera 64MP, Sạc nhanh 65W', 5)
INSERT INTO SANPHAM 
VALUES ('Iphone13', 'Iphone13.jpg', 22000000, N'128GB, Chip A15 Bionic', 6)
INSERT INTO SANPHAM 
VALUES ('Iphone14Pro', 'Iphone14Pro.jpg', 28000000, N'256GB, Dynamic Island', 6)
INSERT INTO SANPHAM 
VALUES ('Bphone2023', 'Bphone2023.jpg', 12000000, N'Flagship Việt Nam', 7)
INSERT INTO SANPHAM 
VALUES ('Xiaomi13', 'Xiaomi13.jpg', 16000000, N'Leica camera, Snapdragon 8 Gen 2', 8)
INSERT INTO SANPHAM 
VALUES ('VivoV27', 'VivoV27.jpg', 8900000, N'Camera selfie 50MP', 9)
INSERT INTO SANPHAM 
VALUES ('RealmeGT3', 'RealmeGT3.jpg', 14000000, N'Sạc nhanh 240W', 10)

-- BẢNG KHACHHANG
INSERT INTO KHACHHANG VALUES (N'Nguyễn Văn An', '0912345678', 'Nam', N'Điện thoại, công nghệ', 'an.nguyen@email.com', 'password123')
INSERT INTO KHACHHANG VALUES (N'Trần Thị Bình', '0923456789', N'Nữ', N'Chụp ảnh, mạng xã hội', 'binh.tran@email.com', 'binh456')
INSERT INTO KHACHHANG VALUES (N'Lê Minh Cường', '0934567890', 'Nam', N'Game, thể thao điện tử', 'cuong.le@email.com', 'cuong789')
INSERT INTO KHACHHANG VALUES (N'Phạm Thu Hà', '0945678901', N'Nữ', N'Thời trang, làm đẹp', 'ha.pham@email.com', 'ha012')
INSERT INTO KHACHHANG VALUES (N'Hoàng Đức Dũng', '0956789012', 'Nam', N'Công nghệ, kinh doanh', 'dung.hoang@email.com', 'dung345')
INSERT INTO KHACHHANG VALUES (N'Vũ Thị Lan', '0967890123', N'Nữ', N'Du lịch, nhiếp ảnh', 'lan.vu@email.com', 'lan678')
INSERT INTO KHACHHANG VALUES (N'Đặng Quang Huy', '0978901234', 'Nam', N'Âm nhạc, giải trí', 'huy.dang@email.com', 'huy901')

-- BẢNG GIOHANG
INSERT INTO GIOHANG VALUES (1, 3, 2, GETDATE())
INSERT INTO GIOHANG VALUES (2, 5, 1, GETDATE())
INSERT INTO GIOHANG VALUES (3, 7, 1, GETDATE())
INSERT INTO GIOHANG VALUES (4, 12, 1, GETDATE())
INSERT INTO GIOHANG VALUES (5, 9, 2, GETDATE())
INSERT INTO GIOHANG VALUES (6, 6, 1, GETDATE())
INSERT INTO GIOHANG VALUES (7, 11, 1, GETDATE())

-- Kiểm tra giá trị hiện tại của IDENTITY
DBCC CHECKIDENT ('GIOHANG');

-- Reset IDENTITY về 0 (để lần chèn tiếp theo bắt đầu từ 1)
DBCC CHECKIDENT ('GIOHANG', RESEED, 0);


SELECT * FROM LOAI
SELECT * FROM SANPHAM
SELECT * FROM KHACHHANG
SELECT * FROM GIOHANG

DELETE FROM GIOHANG
WHERE MAGH BETWEEN 1 AND 7